base:
  project : "Customer_Churn_Prediction"
  random_state: 42
  target: Churn

data_source:
  gdrive_source: Original_data/Churn.csv

load_data:
  raw_data_csv: data/raw/Churn.csv

filter_data:
  filter_data_csv: data/filtered/Churn.csv

select_data:
  select_data_csv: data/select/Churn.csv

split_data: 
  train_path: data/processed/CC_train.csv
  test_path: data/processed/CC_test.csv
  test_size: 0.2

estimators:
  Logistic:
    Params:
      max_iter: 100
      class_weight: 'dict'
      penalty: 'l2'

model_dir: models

report:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib